# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job: unity
  displayName: Unity Build
  variables:
    installCached: false
  condition: or( not(variables['unity.username']),not(variables['unity.password']))
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: echo Add other tasks to build, test, and deploy your project.
    displayName: 'Run a multi-line script'
